---
- name: Generate file content from ansible facts
  hosts: all
  become: true

  tasks:
    - name: create /var/www/ directory
      file:
        path: /var/www/
        state: directory
        mode: 1777
        owner: root
        group: root

    - name: Generate file content using template
      template:
        src: system_info.j2
        dest: /var/www/system_info
        owner: root
        group: root
        mode: 1777
