---
- name: Check connectivity between nodes
  hosts: all
  tasks:
  - name: Use ping module for connectivity
    ping:
    register: output

  - name: Display the output
    debug:
      msg: "{{ output }}"
