---
- name: create user accounts for all servers
  hosts: all
  become: true
  vars_files:
    - secret.yml
  
  tasks:
  - name: Creating user from secret.yml
    user:
      name: "{{ username }}"
      password: "{{ passhash }}"
