---
- name: Modify the file content
  hosts: all
  become: true

  tasks:
    - name: Add content to proxy hosts group
      copy:
        content: Proxy
        dest: /etc/issue
      when: inventory_hostname in groups.proxy

    - name: Add content to Test hosts group
      copy:
        content: Test
        dest: /etc/issue
      when: inventory_hostname in groups.test

    - name: Add content to database hosts group
      copy:
        content: databse
        dest: /etc/issue
      when: inventory_hostname in groups.database

    - name: Add content to webservers hosts group
      copy:
        content: webservers
        dest: /etc/issue
      when: inventory_hostname in groups.webservers

