---
- name: install packages
  hosts: proxy,database
  become: true
  
  tasks:
    - name: install tcpdump and mailx
      yum:
        name:
          - tcpdump
          - mailx
        state: latest
      when: inventory_hostname in groups['proxy'] 

    - name: install lsof and mailx
      yum:
        name:
          - lsof
          - mailx
        state: latest
      when: inventory_hostname in groups['database']  
