---
- name: Create the users 
  hosts: all
  become: true
  vars_files:
    - user_list.yml
    - secret.yml

  tasks:
    - name: create the users in webservers host group
      user:
        name: "{{ item.username }}"
        state: present
        uid: "{{ item.uid }}"
        groups: wheel
        append: true
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/bash
      when:  
        - item.uid < 1999 
        - inventory_hostname in groups['webservers']
      loop: "{{ users }}"
              

    - name: create the users in database host group
      user:
        name: "{{ item.username }}"
        state: present
        uid: "{{ item.uid }}"
        groups: wheel
        append: true
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/bash
      when:
        - item.uid > 2000
        - inventory_hostname in groups['database']
      loop: "{{ users }}"

