---
- name: Create a web content 
  hosts: all
  become: true

  tasks:
    - name: create webdev group
      group:
        name: webdev
        state: present 

    - name: create a directory
      file:
        path: /webdev
        state: directory
        group: webdev
        mode: 2775

    - name: Unlink /var/www/html/webdev
      file:
        path: /var/www/html/webdev
        state: absent
      tags: remove    

    - name: Create a symlink
      file:
        src: /webdev 
        dest: /var/www/html/webdev
        group: webdev
        mode: 2775
        state: link

    - name: Add content
      copy:     
        content: Developemnt
        dest: /webdev/index.html 
